name = input("Please enter your name: ")
surname = input("Please enter your surname: ")
age = input("Please enter your age: ")
degree = input("Please enter your degree: ")
print(f"Username: {name} {surname}\nAge: {age}\nDegree obtained: {degree}")
